CC ?= cc
CFLAGS += -std=gnu99 -s -Os -Wno-address-of-packed-member
LIBS = -lz
SRC_FILES = *.c crypto/*.c

all: dvtws

dvtws: $(SRC_FILES)
	$(CC) $(CFLAGS) -o dvtws $(SRC_FILES) $(LDFLAGS) $(LIBS)

clean:
	rm -f dvtws
