CC ?= cc
OPTIMIZE ?= -Os
MINSIZE ?= -flto=auto -ffunction-sections -fdata-sections -fno-unwind-tables -fno-asynchronous-unwind-tables
CFLAGS += -std=gnu99 -s $(OPTIMIZE) $(MINSIZE) -Wno-address-of-packed-member
LDFLAGS += -Wl,--gc-sections
LIBS = -lz
SRC_FILES = *.c crypto/*.c

all: dvtws

dvtws: $(SRC_FILES)
	$(CC) $(CFLAGS) -o dvtws $(SRC_FILES) $(LIBS) $(LDFLAGS)

clean:
	rm -f dvtws
